### ISSUE TITLE
Cannot see home screen text and some menu text on Linux

### ISSUE THREAD

**Issue by nwpulverizer** [SoftFever/OrcaSlicer#2482]
### OrcaSlicer Version

1.7.0

### OS version

Arch Linux - Qtile WM

### Additional system information

CPU: i7 8700K
Memory: 32GB ddr4
GPU: RTX 3070

### Printer

Bambu P1s

### How to reproduce

1. Install orca slicer on Arch Linux. I am using Qtile and my window manager, but trying on others such as lxqt does not change the effect. 
2. Open Orca slicer
3. View home page or 
4. Press the prepare tab 
5. Click gear icon at the top next to printer

### Actual results

No text is visible. Mousing over items indicates that they are there, but there is something going on with the actual text. 
![home_orca](https://github.com/SoftFever/OrcaSlicer/assets/62257977/878b36e2-856e-4875-a671-4b7ca37c9df7)
![printer_page](https://github.com/SoftFever/OrcaSlicer/assets/62257977/79d6a106-053b-4054-8b66-0b0b76f5737b)

### Expected results

Be able to read text on home screen or printer screen. Cannot add new printers because of this. 

### Project file & Debug log uploads

[debug_Sat_Oct_21_17_22_31_15293.log.txt](https://github.com/SoftFever/OrcaSlicer/files/13062472/debug_Sat_Oct_21_17_22_31_15293.log.txt)
[Untitled.3mf.gz](https://github.com/SoftFever/OrcaSlicer/files/13062473/Untitled.3mf.gz)

### Checklist of files to include

- [X] Log file
- [X] Project file

**Comment by nwpulverizer** [comment]
potentially related to #1344, #883

**Comment by TexZeTech** [comment]
I do have this problem on my main system running Nvidia proprietary drivers but not on my laptop which doesn't have a dedicated GPU and is most likely running video-linux. They are both running Manjaro.

I'm really tempted to blow away my system and see if that would fix it but more and more I'm suspecting something with the Nvidia drivers as darco415 said they tryied out Nouveua drivers in https://github.com/SoftFever/OrcaSlicer/issues/920#issuecomment-1767570850

Desktop:
```
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1080] vendor: ASUSTeK driver: nvidia
    v: 535.113.01 alternate: nouveau,nvidia_drm non-free: 535.xx+
    status: current (as of 2023-09) arch: Pascal code: GP10x
    process: TSMC 16nm built: 2016-21 pcie: gen: 3 speed: 8 GT/s lanes: 8
    link-max: lanes: 16 bus-ID: 01:00.0 chip-ID: 10de:1b80 class-ID: 0300
  Display: x11 server: X.Org v: 21.1.8 with: Xwayland v: 23.2.1
    compositor: kwin_x11 driver: X: loaded: nvidia gpu: nvidia,blackmagic-io
    display-ID: :0 screens: 1
```
[Desktop_debug_Tue_Oct_31_17_26_41_41099.log](https://github.com/SoftFever/OrcaSlicer/files/13222011/Desktop_debug_Tue_Oct_31_17_26_41_41099.log)

I also used the command `journalctl -n 1500 > Desktop_journalctl.txt` 

[Desktop_journalctl.txt](https://github.com/SoftFever/OrcaSlicer/files/13222074/Desktop_journalctl.txt)




Laptop:
```
  Display: x11 server: X.Org v: 21.1.8 compositor: kwin_x11 driver: X:
    loaded: modesetting alternate: fbdev,vesa dri: crocus gpu: i915
    display-ID: :0 screens: 1
```
